all: module.a

CXXFLAGS += -Wall -Wextra -fsanitize=address,fuzzer -std=c++20 -I ../../include
PYTHON_CFLAGS := $(shell python3-config --includes)
PYBITCOINKERNEL_LIB := ./pybitcoinkernel_lib.py

module.a: module.o  $(PYBITCOINKERNEL_LIB)
	$(AR) rcs $@ $^
	ranlib $@

$(PYBITCOINKERNEL_LIB):
	cp pybitcoinkernel_lib.py ../../main.py

module.o: module.cpp module.h
	$(CXX) $(CXXFLAGS) $(PYTHON_CFLAGS) -I . -fPIC -c $< -o $@

format:
	clang-format -i ./module.cpp ./module.h
	black ./pybitcoinkernel_lib.py

check-format:
	clang-format -Werror --fail-on-incomplete-format -n ./module.cpp ./module.h
	black --check ./pybitcoinkernel_lib.py

clean:
	rm -rf *.o *.a ./pybitcoinkernel_lib/pybitcoinkernel_lib.o ../../main.py
